#' @title Generate a parameter file for an univariate Wombat analysis
#'
#' @description Produce a parameter file to be used for an univariate Wombat
#'   run.
#'
#' @details IMPORTANT NOTE: the variance starting values used as arguments
#'   must be less than the variance of the trait (after the trait is
#'   multiplied by \code{trait.factor} in \code{\link{wombat.write.data}})-
#'   If this is not the case, Wombat will wait for a user input confirming
#'   that the run has to be made using large variance, and the R script will
#'   freeze waiting for this input.
#'
#' @param trait name of the trait to be analysed (\code{string}).
#' @param pedigree.file path to the pedigree file (e.g. generated by
#'   \code{\link{wombat.write.pedigree}}).
#' @param data.file path to the data file (e.g. generated by
#'   \code{\link{wombat.write.data}}).
#' @param var.residual numerical, initial value for residual variance.
#' @param var.animal numerical, initial value for animal variance.
#' @param var.mother numerical, initial value for maternal effect variance.
#' @param maternal.effect \code{Boolean}, should maternal effect be included
#'   as a random factor?
#' @param file.path path to save the parameter file. This path should end with
#'   \code{".par"}.
#'
#' @return Nothing.
#'
#' @examples
#' # generate a random pedigree structure for 20 offsprings, using 5 different
#' # sires and 7 different dams
#' set.seed(4)
#' animal_id = 1:20
#' sire_id = sample(1:5, size = 20, replace = T)
#' dam_id = sample(1:7, size = 20, replace = T)
#'
#' # generate some random traits
#' weight = rnorm(n = 20, mean = 50)
#' length = rnorm(n = 20, mean = 100)
#'
#' # assemble the information into one data frame
#' ped_pheno_data = data.frame(animal_id, sire_id, dam_id, weight, length)
#' ped_pheno_data
#'
#' # save the files
#' wombat.write.pedigree(data = ped_pheno_data, animal.id = "animal_id",
#'   father.id = "sire_id", mother.id = "dam_id", convert.pedigree = T,
#'   file.path = "toto.ped")
#' wombat.write.data(data = ped_pheno_data, trait = "weight",
#'   animal.id = "animal_id", father.id = "sire_id", mother.id = "dam_id",
#'   write.mother = T, trait.factor = 2, convert.pedigree = T,
#'   filter.unknown.mother = T, file.path = "toto.dat")
#' wombat.write.parameters(trait = "weight", pedigree.file = "toto.ped",
#'   data.file = "toto.dat", var.residual = 2, var.animal = 2,
#'   var.mother = 2, maternal.effect = T, file.path = "toto.par")
#'
#' @export
#' 

wombat.write.parameters = function(trait, pedigree.file, data.file, var.residual,
                                 var.animal, var.mother = NA, 
                                 maternal.effect = F, file.path) {

  # check that the path ends with ".par"

  stopifnot(grepl("\\.par$", file.path))
  
  # open the file
  
  f = file(file.path, "w")
  
  cat("# A single optional comment line of up to 74 characters\n", file = f)
  
  cat("COMMENT WOMBAT ", trait, "\n", file = f, sep = "")
  
  cat("# The type of analysis to be performed. In this case a UNIvariate analysis\n", file = f)
  
  cat("ANALYSIS UNI\n", file = f)
  
  cat("# Name the pedigree file, assuming it is in the same folder as the parameter file\n", file = f)
  
  cat("PEDS ", pedigree.file, "\n", file = f, sep = "")
  
  cat("# Name the data file, assuming it is in the same folder as the parameter file\n", file = f)
  
  cat("DATA ", data.file, "\n", file = f, sep = "")
  
  cat("# Description of the data file\n", file = f)
  
  cat("# Each variable to be fitted in the model needs to be followed by\n", file = f)
  
  cat("# the maximum number of levels\n", file = f)
  
  cat("ANIMAL 1000\n", file = f)
  
  cat("MOTHER 1000\n", file = f)
  
  cat("VALUE_FOR_ANALYSIS", "\n", file = f, sep = "")
  
  cat("END DATA\n", file = f)
  
  cat("# Model specification\n", file = f)
  
  cat("# Type of effect (FIXed, COVariate, RANdom) and variable name\n", file = f)
  
  cat("# NRM indicates that a pedigree is available for ANIMAL\n", file = f)
  
  cat("MODEL\n", file = f)
  
  cat("RAN ANIMAL NRM\n", file = f)
  
  if (maternal.effect == T) {
    
    cat("RAN MOTHER\n", file = f)
    
  }
  
  cat("# The trait to be analysed\n", file = f)
  
  cat("TRAIT ", "VALUE_FOR_ANALYSIS", "\n", file = f, sep = "")
  
  cat("END\n", file = f)
  
  cat("# Specify starting values and the number of rows and columns in the matrix\n", file = f)
  
  cat("# These are not very important here\n", file = f)
  
  cat("VAR residual 1\n", file = f)
  
  cat(var.residual, "\n", file = f, sep = "")
  
  cat("VAR ANIMAL 1\n", file = f)
  
  cat(var.animal, "\n", file = f, sep = "")
  
  if (maternal.effect == T) {
    
    cat("VAR MOTHER 1\n", file = f)
    
    cat(var.mother, "\n", file = f, sep = "")
    
  }
  
  close(f)
  
}

